import { createValidator } from './src/validator-proxy'

export const required = createValidator('required')
export const email = createValidator('email')
export const alpha = createValidator('alpha')
export const alphaNum = createValidator('alphaNum')
export const and = createValidator('and')
export const between = createValidator('between')
export const decimal = createValidator('decimal')
export const integer = createValidator('integer')
export const ipAddress = createValidator('ipAddress')
export const macAddress = createValidator('macAddress')
export const maxLength = createValidator('maxLength')
export const maxValue = createValidator('maxValue')
export const minLength = createValidator('minLength')
export const minValue = createValidator('minValue')
export const not = createValidator('not')
export const numeric = createValidator('numeric')
export const or = createValidator('or')
export const requiredIf = createValidator('requiredIf')
export const requiredUnless = createValidator('requiredUnless')
export const sameAs = createValidator('sameAs')
export const url = createValidator('url')
